columnas_eliminar:
  - 'Padecimiento'
  - 'Acumulado_anio_anterior'

valores_sustituir:
  - columna_objetivo: "Entidad"
    texto_a_reemplazar: "Distrito Federal"
    texto_sustituto: "Ciudad de MÃ©xico"
    

registros_eliminar:
  - nombre: "Semana"
    valor:  53
