reporte_EDA:
  filtro_padecimiento: "Alzheimer"
  nombre_reporte: "EDA_${reporte_EDA.filtro_padecimiento}"
  titulo_reporte: "Análisis Exploratorio de Datos"
  subtitulo_reporte: "Padecimiento: ${reporte_EDA.filtro_padecimiento} (RAW Data)"
  estilo_fuente: "DejaVu Sans"
  max_cols: 10


reporte_clean_dataset:
  nombre_reporte: "EDA_${reporte_EDA.filtro_padecimiento} (Clean Data)"
  titulo_reporte: "Análisis Exploratorio de Datos"
  subtitulo_reporte: "Padecimiento: ${reporte_EDA.filtro_padecimiento} (Clean Data)"
  estilo_fuente: "DejaVu Sans"
  max_cols: 10